### ISSUE TITLE
Proposal to remove the -= contract, because it modifies the code.

### ISSUE THREAD

**Issue by x1024** [disnet/contracts.coffee#1]
In general, the "-=" contract seems like a code-smell magnet. The only time it could be useful would be when someone writes bad code, which is actually what the library aims to prevent from happening.

From the manual:

```
Functions that get new inserted automatically if it was left out.

f :: (Num) -=> Num
f = (n) -> # ...
#...

g = f 42      # ok: converted to g = new f 42
g = new f 42  # ok
```

IMHO, this is actually very harmful because it causes the contracts to change the code's meaning.  
This means that bad code WILL get written.

I'm not sure if using the coffee compiler still adds "new" to functions having "-=" contracts if compilation is set with contracts disabled, but even if it does, it still seems like a bad idea.

**Comment by disnet** [comment]
Probably don't want to go removing things just yet but you bring up a good point. Contracts usually just restrict behavior not add to it like "-=>".

The thing is, it's pretty useful. It's actually a sort of common pattern in JS to do this by hand (jQuery does it I think). I'm torn on this one.

> I'm not sure if using the coffee compiler still adds "new" to functions having "-=" contracts if compilation is set with contracts disabled, but even if it does, it still seems like a bad idea.

New is not added if contracts are disabled (happens inside the function contract trap: https://github.com/disnet/contracts.js/blob/master/src/contracts.js#L431)

**Comment by disnet** [comment]
Just realized that this is a bigger issue. We want to allow contracts to be disabled in production environments for performance and compatibility (missing Proxy) reasons. But if we allow contracts that change the semantics we'll have code that does one thing when contracts are enabled and another when they are disabled.

I'll remove "-=>".

**Comment by disnet** [comment]
https://github.com/disnet/contracts.coffee/commit/f3affff34201fc5a019661429e721170c7143952
