### ISSUE TITLE
Convention based contracts

### ISSUE THREAD

**Issue by JulianBirch** [disnet/contracts.coffee#13]
I know this completely breaks the Haskell style syntax, but it would be very cool if you could specify
- any parameter that ends in Model extends the model class
- any parameter called name is a string

**Comment by disnet** [comment]
Interesting idea. You mean adding contracts to every function in a file that has params matching those rules?

What worries me more than breaking the syntax is that this would be implicitly adding contracts in cases the programmer might not be expecting. Contracts have a cost and my feel is that explicit is better than implicit (especially since you have to call `.use()` before using a contracted value).

Besides less typing what is the benefit?

**Comment by JulianBirch** [comment]
Yeah, it's probably not that useful while you still have to call <code>.use()</code>.  However, the real benefit is actually for programming in the large.  If you can have a central file that specifies contracts, it makes it very easy to read large chunks of code since your conventions are guaranteed to be observed.

And yes, you will sometimes get nasty surprises, but in general terms those will be where you unintentionally violated your coding conventions.  It gives you early pain (change the variable name) as opposed to late pain (the function is misunderstood by other programmers.)

**Comment by disnet** [comment]
It seems to me that contracts are kind of philosophically opposed to doing things implicitly (even apart from contracts.coffee's current `.use()` crutch). Contracts are all about explicitly stating your assumptions but convention contracts make the assumptions implicit (the actual contracts are separated out into a different file that we then have to go look at).

Seems like it would be better (especially when "programming in the large") to write down your assumptions explicitly as a contract at the definition site than to rely on a convention that we post-hoc apply an implicit contract to.

True, if we use explicit contracts we can break conventions (`name` is a `Str` here but `Num` there) but we are not confusing other programers (we've explicitly stated and enforced what it is). But implicit contracts have a much larger potential confusion surface. Now the programmer must keep track of which patterns/conventions will wind up as a contract.

**Comment by JulianBirch** [comment]
I think I quite like the idea of implicit contracts.  (Admittedly, most Haskell code I've seen declares signatures even when it isn't necessary.)  It would save me a lot of debugging time, for instance, if when I wrote (Backbone)

```
charges.detect (m) -> name == m.get 'name'
```

That I was guaranteed that any parameter in my code called "m" was, in fact, a Backbone model.

Anyway, thanks for your time.  I'm closing the ticket.

**Comment by disnet** [comment]
Thanks for the discussion!
