### ISSUE TITLE
Npm package

### ISSUE THREAD

**Issue by ghost** [disnet/contracts.coffee#18]
Could there be a npm way to install it again?

```
npm install contracts.coffee
```

And also compiling it with one global command instead, eg:

```
contracts -C my_file.coffee
```

instead of me having to write this:

```
node --harmony_proxies bin/coffee -CL test.coffee
```

**Comment by disnet** [comment]
I can definitely look at the npm installer.

The `bin/coffee` is passing the proxy flag to node so you should just be able to do:

```
bin/coffee -CL test.coffee
```

Are you trying the latest from master?

**Comment by ghost** [comment]
The problem is that I don't want to navigate to the bin/coffee script. Would be easier to just run a global binary that npm could install right?

Yeah I am on the latest.

**Comment by disnet** [comment]
Ah! I see what you're saying.

I'll get it into npm but if you want to install it globally in the mean time you can do a `cake install` which will put everything in `/usr/local` (or the path of your choice via the `--prefix` flag).

**Comment by disnet** [comment]
We're now published in npm! Do a `npm install -g contracts.coffee` to get it.

**Comment by ghost** [comment]
Awesome!
