### ISSUE TITLE
Latest coffee-script?

### ISSUE THREAD

**Issue by ghost** [disnet/contracts.coffee#19]
I have a web app that I woud want to use contracts for.

But I wonder if contacts.coffee is always using the latest coffee so I know that the new features could be used.

**Comment by disnet** [comment]
Yep, it will be tracking upstream CoffeeScript. At the moment master is a few weeks behind (so it doesn't have 1.1.4) but I'll be updating it in the next day or so.

I also intend to keep tagged npm releases synced with whatever is the stable release of CoffeeScript in the future.

**Comment by ghost** [comment]
Yeah keeping the tag in sync with CS would be great way for users to know what CS version we are using. Please do so.
