### ISSUE TITLE
read environment variable that turns off/on --contracts

### ISSUE THREAD

**Issue by gregwebs** [disnet/contracts.coffee#27]
I already have code in place to automatically execute coffeescript that I don't want to change. This also makes it easy to define that there should not be contracts in the production environment.

What do you suggest for the variable name? CONTRACTS_COFFEE_ENABLED

--contracts on the command line would override this setting.

**Comment by disnet** [comment]
Good idea! That name is probably fine.

**Comment by gregwebs** [comment]
see #29
