### ISSUE TITLE
document building from source

### ISSUE THREAD

**Issue by gregwebs** [disnet/contracts.coffee#28]
I tried the coffescript way of `sudo bin/cake install`
It complained of no README, so I copied README.md to README and installed again.
However, it doesn't seem to be working.

Now I am trying just the regular install instructions and I get:

```
/usr/lib/node_modules/contracts.coffee/bin/coffee --eval --contracts "id :: (Num) -> Num\nid = (x) -> x\nid 5\n"

Error: Cannot find module 'contracts.js'
```

**Comment by disnet** [comment]
Install contracts.js via `npm install contracts.js`.

**Comment by gregwebs** [comment]
I get

```
Error: No compatible version found: contracts.js
npm ERR! No valid targets found.
npm ERR! Perhaps not compatible with your version of node?
...

npm ERR! node -v v0.6.11
npm ERR! npm -v 1.1.0-2
```

I guess I will downgrade node to 0.5.x

**Comment by disnet** [comment]
Yeah, unfortunately node downgraded V8 in 0.6.x and broke proxy support.

**Comment by gregwebs** [comment]
getting closer

```
> npm install contracts.js                                        
contracts.js@0.2.0 ./node_modules/contracts.js 

> coffee --contracts --eval "a :: Num -> Num\na = (x) -> x\na 5\n"
ReferenceError: a is not defined
    at .:65:7
    at .:68:6
    at .:6:5
    at Object.<anonymous> (.:10:2)
    at Module._compile (module.js:432:26)
    at Object.run (/usr/local/lib/coffee-script/lib/coffee-script/coffee-script.js:68:25)
    at /usr/local/lib/coffee-script/lib/coffee-script/command.js:135:29
    at Object.run (/usr/local/lib/coffee-script/lib/coffee-script/command.js:56:27)
    at Object.<anonymous> (/usr/local/lib/coffee-script/bin/coffee-node:5:41)
    at Module._compile (module.js:432:26)
```

**Comment by disnet** [comment]
Does it work if you compile a script? Might have a bug in --eval.

On Saturday, February 25, 2012, Greg Weber wrote:

> getting closer
> 
> ```
> > npm install contracts.js
> contracts.js@0.2.0 ./node_modules/contracts.js
> 
> > coffee --contracts --eval "a :: Num -> Num\na = (x) -> x\na 5\n"
> ReferenceError: a is not defined
>    at .:65:7
>    at .:68:6
>    at .:6:5
>    at Object.<anonymous> (.:10:2)
>    at Module._compile (module.js:432:26)
>    at Object.run
> (/usr/local/lib/coffee-script/lib/coffee-script/coffee-script.js:68:25)
>    at /usr/local/lib/coffee-script/lib/coffee-script/command.js:135:29
>    at Object.run
> (/usr/local/lib/coffee-script/lib/coffee-script/command.js:56:27)
>    at Object.<anonymous>
> (/usr/local/lib/coffee-script/bin/coffee-node:5:41)
>    at Module._compile (module.js:432:26)
> ```
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/disnet/contracts.coffee/issues/28#issuecomment-4173452

## 

-Tim

**Comment by gregwebs** [comment]
```
> cat a.coffee 
a :: Num -> Num
a = (a) -> a
a 5
```

```
>  coffee --contracts a.coffee
Error: In a.coffee, Parse error on line 1: Unexpected 'CALL_START'
    at Object.parseError (/usr/local/lib/coffee-script/lib/coffee-script/parser.js:595:11)
    at Object.parse (/usr/local/lib/coffee-script/lib/coffee-script/parser.js:671:22)
    at /usr/local/lib/coffee-script/lib/coffee-script/coffee-script.js:40:22
    at Object.run (/usr/local/lib/coffee-script/lib/coffee-script/coffee-script.js:68:34)
    at /usr/local/lib/coffee-script/lib/coffee-script/command.js:135:29
    at /usr/local/lib/coffee-script/lib/coffee-script/command.js:110:18
    at [object Object].<anonymous> (fs.js:108:5)
    at [object Object].emit (events.js:64:17)
    at afterRead (fs.js:1074:12)
    at Object.wrapper [as oncomplete] (fs.js:246:17)
```

It seems like it isn't working, but it does get past the --contracts argument, whereas if I give an invalid argument it will fail.

**Comment by disnet** [comment]
Odd. Are you sure the `coffee` binary you are using is the contracts.coffee one and not the normal CoffeeScript? Might be some pathing issues going on.

**Comment by gregwebs** [comment]
So I realized I can just use the bin/coffee in the project, but the result is the same

```
> ./bin/coffee --contracts a.coffee 
Error: In a.coffee, Parse error on line 1: Unexpected 'CALL_START'
    at Object.parseError (/home/gweber/proj/js/contracts.coffee/lib/coffee-script/parser.js:595:11)
    at Object.parse (/home/gweber/proj/js/contracts.coffee/lib/coffee-script/parser.js:671:22)
    at /home/gweber/proj/js/contracts.coffee/lib/coffee-script/coffee-script.js:40:22
    at Object.run (/home/gweber/proj/js/contracts.coffee/lib/coffee-script/coffee-script.js:68:34)
    at /home/gweber/proj/js/contracts.coffee/lib/coffee-script/command.js:135:29
    at /home/gweber/proj/js/contracts.coffee/lib/coffee-script/command.js:110:18
    at [object Object].<anonymous> (fs.js:108:5)
    at [object Object].emit (events.js:64:17)
    at afterRead (fs.js:1074:12)
    at Object.wrapper [as oncomplete] (fs.js:246:17)
```

**Comment by disnet** [comment]
Ah! The problem is parens are missing from the argument contract. Should be:

```
a :: (Num) -> Num
a = (a) -> a
```

Function contracts use the same syntax rule regarding parens as normal CoffeeScript functions.

**Comment by gregwebs** [comment]
doh! Haskell user here :) That is a good design choice for
coffeescript actually though.
BTW, the explanation of contracts as better than types is a little
strange (one is not simply better than the other, they are a tradeoff)
and strictly incorrect. Dependent types (which not even Haskell has,
but are in languages like Agda) can analyze many more properties.

My only problem now is I am getting:
__contracts is not defined

I do have contracts.js loaded in the window.

On Sat, Feb 25, 2012 at 12:58 PM, Tim Disney
reply@reply.github.com
wrote:

**Comment by disnet** [comment]
If you do `npm ls` in the same directory does it print out contracts.js?

**Comment by gregwebs** [comment]
sorry, my message was confusing. node is working perfectly - I am
trying to get it to work in the browser now. My browser version is
Mozilla/5.0

On Sat, Feb 25, 2012 at 1:47 PM, Tim Disney
reply@reply.github.com
wrote:

**Comment by disnet** [comment]
Is contracts.js loaded first? ie:

```
<script type="text/javascript" src="lib/contracts/contracts.js"></script>
<script type="text/javascript" src="a.js"></script>
```

vs.

```
<script type="text/javascript" src="a.js"></script>
<script type="text/javascript" src="lib/contracts/contracts.js"></script>
```

**Comment by disnet** [comment]
Re: contracts vs. types. I definitely didn't mean to imply contracts
are strictly better than types, they are absolutely complimentary. I
threw in a bit of tongue-in-cheek snark at haskell's expense on
the website to appeal to the dynamic language people who's guard
immediately comes up on seeing anything that smacks of static types.
Playing a little bit of politics but if we can get them halfway
there eventually we'll get them all the way there :)

Also, strictly speaking contracts can restrict more properties than
even a dependent types system since dependent types run into undecidability
problems. Of course you don't know until runtime that a contract is
violated (or never if you don't exercise that particular path).

BTW, I'm a PL PhD student and haskell user (the syntax similarities are no
accident!) so axiomatically I love types :)

**Comment by gregwebs** [comment]
I did have that correct. I was using the -b --bare option, which seems
to be required not to be used (would be good to document that also).

So I think I am all ready to start contracting!

On Sat, Feb 25, 2012 at 2:13 PM, Tim Disney
reply@reply.github.com
wrote:

**Comment by gregwebs** [comment]
Thanks so much for all your help!

I am hoping to get all the way there myself at least. I think a lot of the work has been done already in Roy.js. I opened a ticket suggesting they switch to coffee.contracts to get a mature implementation: https://github.com/pufuwozu/roy/issues/119
