### ISSUE TITLE
Following context contract not possible in custom contract definition

### ISSUE THREAD

**Issue by TobiaszCudnik** [disnet/contracts.coffee#38]
Following context contract not possible in custom contract definition:

``` coffeescript
TSignalGetter = ? (@{ emit: (->Any), on: (->Any) }) -> TSignalRet
```

**Comment by disnet** [comment]
Yeah, this is a bug because of a hack I'm doing in the rewriter to disambiguate `@` for the grammar. The disambiguation only runs in `::` contract statements but should also happen in `?` contract statements.
