### ISSUE TITLE
Unable to use an object attr as contract

### ISSUE THREAD

**Issue by TobiaszCudnik** [disnet/contracts.coffee#39]
Unable to use an object attr as contract. This isn't a big issue, but worth noting.

``` coffeescript
e.signal :: -> ($.TSignalMethod)
e.signal = e.signal
```

**Comment by disnet** [comment]
Sorry for the delayed response here.

I actually think you can use an object attr. As long as `$.TSignalMethod` is a contract it should work. Though you'll need to use the `!` notation:

``` coffee
e.signal :: -> !$.TSignalMethod
e.signal = e.signal
```

**Comment by gregwebs** [comment]
should this be closed?
