### ISSUE TITLE
custom contract definitions not removed

### ISSUE THREAD

**Issue by gregwebs** [disnet/contracts.coffee#41]
cat test.coffee 

```
    Data = ?([...Num or Str])

    getData :: (Data) -> Data
    getData = (arr) -> arr
```

coffee -p test.coffee

```
(function() {
  var Data, getData;

  Data = arr([___(or(Num, Str))]);

  getData = function(arr) {
    return arr;
  };

}).call(this);
```

**Comment by disnet** [comment]
Should work now.

**Comment by gregwebs** [comment]
Thanks, is this released? I installed from npm before. When I tried to cake build it just thrashes my hard drive, not sure what I am doing wrong.

**Comment by disnet** [comment]
Oops! Had a bug in the Cakefile that caused it to spin if contracts.js hadn't been checked out. You'll need to run `git submodule init && git submodule update` for build to work.

Collecting this and a few other fixes into an npm release. Should be up soon.

**Comment by gregwebs** [comment]
Tried out the latest. works great. Thanks!
