### ISSUE TITLE
expected Undefined actual: missing property

### ISSUE THREAD

**Issue by gregwebs** [disnet/contracts.coffee#45]
I would like to define an object property as `Undefined or Str`. However, Undefined appears to have no effect:

``` coffee
UndefC = ?({ myc: -> Undefined })
a :: UndefC
a = {a:'b'}
```

Contract violation: expected <{ myc : () -> Undefined }>, actual: "[missing property: myc]" Value guarded in: TimelineView.js?body=1:73 (value) -- blame is on: TimelineView.js?body=1:73 (value) Parent contracts: { myc : () -> Undefined }
[Break On This Error]

**Comment by disnet** [comment]
The violation message in your example is telling the truth :) The object `a` is missing the property `myc` (it has `a` instead).

Undefined seems to be working for me. Does this work for you? It should complain that calling `a.myc` does not give `undefined`.

``` coffee
UndefC = ?({ myc: -> Undefined })
a :: UndefC
a = {myc:'b'}

do a.myc
```

**Comment by gregwebs** [comment]
Sorry, don't know why I put the `->` in there. The example and error message is roughly the same though without it. Does that make the issue clear then? I would expect Undefined to indicate that the property is missing.

**Comment by disnet** [comment]
There's a difference in JS between an object with a missing property and an object with a property set to `undefined`.

``` js
> o = {myc: undefined}
{ myc: undefined }
> Object.keys(o)
[ 'myc' ]
```

So we need a way to say the property exists and is `undefined`, which is the syntax we have now. But you want a way to say an object does **not** have a property (and to fail if it does) right?

Ah! I think what you want (re-reading your original post) is optional properties. We already have syntax for that:

``` coffee
o = ?({ myc: Str?}) # if property exists it must be a Str
```

Does that work?

**Comment by gregwebs** [comment]
oh, you are quite right! Sorry that I missed optional properties.
