### ISSUE TITLE
empty nested array contracts

### ISSUE THREAD

**Issue by gregwebs** [disnet/contracts.coffee#46]
I tried for a long time to reduce this down to a test case, but I can't (I assume because there is something stateful within contracts.coffee). I have a contract that I have reduced down to this:

``` coffee
nested_arr:: (Any) -> [...[...Any]]
nested_arr = (event) -> []
```

It works fine when I try to reproduce the issue. However, while running a program (that has a lot of contracts), I get this error:

```
Uncaught Error: Contract violation: expected <[...any]>, actual: undefined
Value guarded in: TimelineView.js?body=1:109:30 (value) -- blame is on: TimelineView.js?body=1:109:30 (value)
Parent contracts:
[...[...any]]
(any) -> [...[...any]] 
```

If I change the returned value to `[[]]` it works.

**Comment by gregwebs** [comment]
actually, I don't think the [[]] works.

**Comment by disnet** [comment]
If the error message is telling the truth then the code is trying to assign `undefined` to the array returned from `nested_arr`. Can you confirm that your code is not in fact trying to assign `undefined`?

**Comment by gregwebs** [comment]
yes, my code is in fact the `nested_arr` function. The same input works initially but then later fails.

**Comment by disnet** [comment]
But calling `nested_arr` will return an array wrapped in the `[...[...Any]]` contract. The contract checking of the array is delayed until you actually use it (eg by inserting a value into the array) at a later point. That later point is where I'm guessing you are trying to insert an `undefined`. Eg:

``` coffee
nested_arr:: (Any) -> [...[...Any]]
nested_arr = (event) -> []

my_arr = nested_arr()
# ...
my_arr[0] = undefined  # contract violation is correctly triggered
```

**Comment by gregwebs** [comment]
ahh, now it actually makes sense that this bug would occur in the first place! So here is a complete test case:

``` coffee
nested_arr :: (Any) -> [...[...Any]]
nested_arr = (event) -> []
foo = nested_arr(5)[0]?[0]
```

**Comment by disnet** [comment]
Just to clarify, are you thinking this test case should pass or fail with a contract violation?

It seems to me that the contract violation is correct behavior. The contract is saying the function must return a non-empty array but since the array is empty any use of it should trigger the violation.

**Comment by gregwebs** [comment]
You are right, the contract violation is correct, although I think your explanation is slightly off. The contract states the function must return an array that can be empty but must only contain arrays. Accessing the array returns undefined instead of an array, violating the contract.

This has revealed a deep misunderstanding I had of how contracts.coffee work (I thought objects were checked around function calls). If you could try to make it clear in the docs that contracts stick with the objects and are checked on access, that would be very helpful.

**Comment by disnet** [comment]
Yeah, looks like I definitely need to add a writeup on exactly when contracts are checked.

Interestingly enough, this also shows that we are deferring some checks that could happen eagerly. In general object properties need to be checked lazily because they can be higher-order (a function) which we can't check yet or mutated (and then become something that doesn't agree with the contract). That said, any properties that are first order (`Num`, `Str`, etc.) could easily be checked right away which would improve error messaging.
