### ISSUE TITLE
lib/cofee-script/coffee-script.js not updated since Apr 15

### ISSUE THREAD

**Issue by gregwebs** [disnet/contracts.coffee#47]
I thought this had to also be updated for the latest improvements.

**Comment by disnet** [comment]
Modulo documentation and some unfinished work for #38 that's about when I last committed stuff. So that should be right.

**Comment by gregwebs** [comment]
sorry, I really meant extras/coffee-script.js
I think it is missing the fix for #41

**Comment by disnet** [comment]
Ah! Thanks for the catch!
