### ISSUE TITLE
global contracts to avoid inlined js in all files

### ISSUE THREAD

**Issue by gregwebs** [disnet/contracts.coffee#49]
contracts.coffee is following best practice by not polluting the global scope by default. However, for some of my projects I would be happier with placing the contract variables directly on the window variable: I could avoid 60 lines of boilerplate in every javascript file and just place things on the window once.

**Comment by disnet** [comment]
Are you talking about the boilerplate the compiler spits out (https://github.com/disnet/contracts.coffee/blob/master/src/nodes.coffee#L286) or boilerplate you are writing to access the contract variables directly in your code?

We could get ride of some of the compiler boilerplate (the contract aliasing) but most of it is setting up the module names.

**Comment by gregwebs** [comment]
yeah, the loadContracts. I understand this (aliases & module stuff) is a good default, but I think I only need some of it once before my code is loaded.

**Comment by disnet** [comment]
So we can do some prefixing of the various `Num`, `Str`, etc. contracts to clean up some of the boilerplate (been meaning to do that anyway) but if we drop the module stuff, things won't work right.

Is your main concern the boilerplate getting in the way of readability? That could be fixed just with some better formatting (e.g. collapse the boilerplate to one line).

**Comment by gregwebs** [comment]
Yeah, I am concerned about readability and creating a need to start by scrolling past boilerplate. I think collapsing the boilerplate into 1 line would be a better default. Perhaps there should be an options to keep the boilerplate expanded for those that want to see how it works, or maybe the Chrome prettifier button will already do this.

**Comment by gregwebs** [comment]
how about this as a starting point: if there are no contracts in the file don't add any contracts boilerplate

**Comment by disnet** [comment]
We actually need the boilerplate in case you load a contracted module even if there are no contracts in the file. But what we can do is minify the boilerplate! Which I just committed. Should have done that 3 months ago...sorry :(

**Comment by disnet** [comment]
Actually, come to think of it we could pair down at least part of the boilerplate if no contracts are detected in the file (the bit that aliases contract names and whatnot, still need to do the right thing when loading an external module). But maybe minification is sufficient?

**Comment by gregwebs** [comment]
yeah, don't bother now that there is minification. thanks!
