### ISSUE TITLE
CONTRACTS_COFFEE_ENABLED isn't honored by module require

### ISSUE THREAD

**Issue by TobiaszCudnik** [disnet/contracts.coffee#50]
CONTRACTS_COFFEE_ENABLED isn't honored by module require, like so:

```
require('contracts.coffee');
```

**Comment by disnet** [comment]
Silly bug, I could really use some contracts in the compiler :)

Thanks for reporting!

**Comment by TobiaszCudnik** [comment]
Would love to see it fixed, can tackle with some hints ;)

On 15 lip 2012, at 04:30, Tim Disney
reply@reply.github.com
wrote:

**Comment by disnet** [comment]
Oh, it should work now. Sorry, didn't mention in the comment.

**Comment by TobiaszCudnik** [comment]
Thx, works very well with [node-dev](https://github.com/fgnass/node-dev), just the line mapping is missing and it'll be transparent.
