### ISSUE TITLE
Voting for contracts.coffee IntelliJ IDEA support

### ISSUE THREAD

**Issue by TobiaszCudnik** [disnet/contracts.coffee#51]
Hi all!

Please vote for contracts.coffee IntellJ IDEA support, as they'ew adding new languages very rapidly and also that's a great JS IDE. I just miss the contracts support (highlighting is a good start).

Thanks!

Link: http://youtrack.jetbrains.com/issue/RUBY-10542

**Comment by disnet** [comment]
I voted! Haven't used intelliJ in a while but it's still my favorite IDE :)

**Comment by TobiaszCudnik** [comment]
Weird relation IMHO ;) They have the best CoffeeScript support and regularly fix my bug reports, so there's a change for good contracts experience (although even with errors it's fine for coding!), hopefully.

**Comment by gregwebs** [comment]
I voted. This ticket should be closed and moved to an editor/IDE support section in the README or website
