### ISSUE TITLE
Uncaught TypeError: <unknown message handler_failed> 

### ISSUE THREAD

**Issue by gregwebs** [disnet/contracts.coffee#52]
```
Uncaught TypeError: <unknown message handler_failed> contracts.js:951
handler.delete contracts.js:951
Ext.define.prepareItems AbstractContainer.js:442
```

I have a function with this signature that works fine:

``` coffee
eventedButton :: (Str, Str, Undefined or {id:Str}) ->
  {ui:Str,text:Str,handler:()->Any,eventListeners:Undefined or [...Any]}
```

When I add an id field:

``` coffee
eventedButton :: (Str, Str, Undefined or {id:Str}) ->
  {id:Str, ui:Str,text:Str,handler:()->Any,eventListeners:Undefined or [...Any]}
```

I get the error message. I verified that the id field is present by logging. I actually want it to be an optional field, that triggers the error also.

**Comment by disnet** [comment]
Strange. From the stacktrace it looks like the error happens when a property is being deleted, but this seems to work fine on contracted objects for me.

What version of node/browser are you using? Do you have a fuller stacktrace?

**Comment by gregwebs** [comment]
Chrome Version 20.0.1132.57. node version v0.6.14

The rest of the stack is non-contracts code.

**Comment by disnet** [comment]
Can you confirm if this still happens on node 0.8.x? Node 0.6 had a bunch of V8 proxy bugs.

**Comment by gregwebs** [comment]
I just installed v0.8.4 and have the same results.

**Comment by gregwebs** [comment]
If I change `Undefined or {id:Str}` to Any it works fine.

**Comment by disnet** [comment]
Humm...still can't reproduce this. I don't suppose you can post a runnable snippet?

**Comment by gregwebs** [comment]
did some significant narrowing down, the below triggers it. If I just apply the id from option to r instead it works fine. This is being handed off to the Ext framework though, not sure if you can reproduce.

``` coffee
eventedButton :: (Undefined or {id:Str}) ->
  {id:Str?, ui:Str}
eventedButton = (options) ->
  r = 
    ui: 'link'
  options ||= {}
  for k,v of r
    options[k] = v
  options
```

**Comment by gregwebs** [comment]
So probably the issue is that the passed in object (options) is being modified. I am not sure if that is a violation of the rules of using the contracts, but a better error message would be nice.

**Comment by disnet** [comment]
Ah! Was finally able to reproduce, it happens when you wrap an object in a proxy twice and then try to delete a property (see referenced commit). This is a bug in V8's handling of proxies since it works just fine in Firefox/SpiderMonkey but fails in both node 0.8.x and chrome 22 (the latest dev channel).

I'll submit a bug to V8. Unfortunately I don't think there's a great workaround until that's fixed.

**Comment by disnet** [comment]
I take it back! There actually was a bug with my code. The proxy delete handler needed to return the result of its delete operation. Just committed a fix to contracts.js but Github isn't showing the commit yet.

Pull down that latest and let me know if that works for you.

**Comment by disnet** [comment]
Ah, here's the fix if you're interested: https://github.com/disnet/contracts.js/commit/ddbd00d3e38f70581571a45542cd7a89257e0a80

**Comment by gregwebs** [comment]
awesome, thanks!
