### ISSUE TITLE
Use direct proxies

### ISSUE THREAD

**Issue by paulmillr** [disnet/contracts.coffee#53]
[Direct proxies](http://wiki.ecmascript.org/doku.php?id=harmony:direct_proxies) is the new cool API. It should be much more performant when it'll be available.

**Comment by disnet** [comment]
Yep! I've been watching the SpiderMonkey [ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=703537) in anticipation :) Haven't found any public tickets for V8 but hopefully they're working on it too.

Should be pretty easy to switch over so I'll do so as soon as it lands.
