### ISSUE TITLE
Add syntax for contracts that are backward compatible with CoffeeScript

### ISSUE THREAD

**Issue by x1024** [disnet/contracts.coffee#9]
**Idea**:
Have an option for the contract library to be backward-compatible with vanilla CoffeeScript

**Expected behavior**:
When compiled with a contracts-enabled compiler, some coffee code with contracts...well, has contracts
When the same code is compiled with a non-modified coffee compiler, it has no contracts but otherwise still compiles and runs.

**Suggested solution**:
Have contracts be embeddable in comments.
I noticed this pattern was actually already used in the contracts.js project.

I've implemented it here:
https://github.com/x1024/contracts.coffee/commit/59b9d02a2c6930a690ca66ba8947b2d44bc6dcc9
(there are a few more commits, but that's the heart of it)

Currently, only single-line contracts are allowed to be backward compatible.

This is valid contract-enabled coffee in my fork:

```
#:: id :: (Num) -> Num
id = (x) -> x
```

If the idea gets accepted, I'll write some tests for it and submit a pull request.

**Comment by disnet** [comment]
Wow, this is awesome!

Bikeshedding the syntax a little:

Not sure I like `#::`. Perhaps `#:`

```
#: id :: (Num) -> Num
id = (x) -> x
```

or maybe just

```
# id :: (Num) -> Num
id = (x) -> x
```

But that might be more likely to conflict with preexisting comments. 

Or we could bring in the meaning of our existing "?" operator:

```
#? id :: (Num) -> Num
id = (x) -> x
```

or even cleaner if less consistent:

```
#? (Num) -> Num
id = (x) -> x
```

What do you think?

**Comment by dherman** [comment]
Interesting idea! I personally find

```
# id :: (Num) -> Num
```

the cleanest.

Dave

**Comment by bolshakov** [comment]
It's brilliant idea! I think the comment should be in a special form. Let's look at over projects:
- Sprockets uses "#=" comments
- Python has "#: "
- Often we type "# =>" to mark comment as output.

So it's easy separate regular comment from comment with special meaning.

**Comment by x1024** [comment]
Initially, I also wanted to have:
    # id :: (Num) -> Num
But then comments don't even get to the rewriter stage, I think.
Or maybe I should've checked for **// id ::** instead of **# id ::**. I'll run another test now.

So that's why I made it to be **#:: id ::**
Any other symbol can be used to signify a contract comment, not just **::**.

I personally like the **#? id ::** syntax because it ties in nicely with the rest of the contracts syntax additions, but I'm open to more suggestions.

**Comment by x1024** [comment]
Today I did some more work and I managed to get this syntax to work:

```
# id :: (Num) -> Num
id = (x) -> x
```

Contracts are now backward-compatible and I think it's the cleanest way to implement backward-compatibility.

Here's the patch:
https://github.com/x1024/contracts.coffee/commit/8fe35f62f75ac382f4fef80122628f0920604554

It's just a couple of lines and has some decent tests writtern for it. Of course, some QA would be greatly appreciated.

I've submitted a pull request.

**Comment by disnet** [comment]
Closing since `.use()` doesn't make this change backward compatible (see discussion in: https://github.com/disnet/contracts.coffee/pull/12)
